[theme]
primaryColor = "#6b4423"  # Marrón oscuro para los elementos principales
backgroundColor = "#f5e6da"  # Marrón clarito para el fondo
secondaryBackgroundColor = "#d1bfa5"  # Marrón medio para elementos secundarios
textColor = "#333333"  # Color del texto
font = "sans serif"  # Fuente del texto